from pathlib import Path

FULL_DATASET_FILE_PREFIX = 'yelp_academic_dataset_'
RESTAURANT_DATASET_FILE_PREFIX = 'yelp_academic_restaurant_dataset_'
FILTERED_DATASET_DIR = 'dataset'
ABS_DATASET_DIR_PATH = Path(__file__).parent.absolute().parent / FILTERED_DATASET_DIR
RESTAURANT_DATASET_FILENAME = ABS_DATASET_DIR_PATH / (RESTAURANT_DATASET_FILE_PREFIX + 'business.json')
RESTAURANT_INDEX_FILENAME = ABS_DATASET_DIR_PATH / 'restaurant_idx.json'
REVIEW_DATASET_FILENAME = ABS_DATASET_DIR_PATH / (RESTAURANT_DATASET_FILE_PREFIX + 'review.json')
REVIEW_CORPUS_FILENAME = ABS_DATASET_DIR_PATH / 'review' / 'review.dat'
REVIEW_CORPUS_CFG_FILENAME = ABS_DATASET_DIR_PATH / 'review' / 'line.toml'
SEARCH_RESULT_COUNT = 10
