prefix = "../dataset"
dataset = "review"
corpus = "line.toml"
index = "idx"

[[analyzers]]
method = "ngram-word"
ngram = 1

[[analyzers.filter]]
type = "icu-tokenizer"
suppress-tags = true

[[analyzers.filter]]
type = "lowercase"

[[analyzers.filter]]
type = "list"
file = "stopwords.txt"

[[analyzers.filter]]
type = "porter2-filter"
